AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EC2KeyPairName:
    Description: >-
      Name of an existing Amazon EC2 key pair to enable SSH or RDP access to the
      instances.
    Type: 'AWS::EC2::KeyPair::KeyName'
    MinLength: '1'
    MaxLength: '255'
    AllowedPattern: '[\x20-\x7E]*'
    ConstraintDescription: Can contain only ASCII characters.
Resources:
  CodeDeployEC2InstancesStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: >-
        http://s3.amazonaws.com/aws-codedeploy-us-east-1/templates/latest/CodeDeploy_SampleCF_Template.json
      TimeoutInMinutes: '60'
      Parameters:
        KeyPairName: !Ref EC2KeyPairName

