version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
  parameter-store:
    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
  install: #commands that CodeBuild runs during installation
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build: #commands that CodeBuild runs before the build
    commands:
      - echo Entered the pre_build phase...
      - docker login -u User -p $LOGIN_PASSWORD
    finally:
      - echo This always runs even if the login command fails 
  build: #commands that CodeBuild runs during the build
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
    finally:
      - echo This always runs even if the install command fails
  post_build: #commands that CodeBuild runs after the build
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

reports: #specifies the report group that the reports are sent to
  arn:aws:codebuild:your-region:your-aws-account-id:report-group/report-group-name-1:
    files:
      - "**/*"
    base-directory: 'target/tests/reports'
    discard-paths: no
  reportGroupCucumberJson: #my-project-reportGroupCucumberJson is created when a build is run
    files:
      - 'cucumber/target/cucumber-tests.xml'
    discard-paths: yes  #test files are placed in the same output directory
    file-format: CUCUMBERJSON # default is JUNITXML

artifacts: #represents information about where CodeBuild can find the build output
  files:
    - target/messageUtil-1.0.jar
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - target/artifact-1.0.jar
      discard-paths: yes
    artifact2:
      files:
        - target/artifact-2.0.jar
      discard-paths: yes
